# Generated by Django 4.2.11 on 2024-07-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homst', '0016_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
