# Generated by Django 4.2.11 on 2024-07-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homst', '0018_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('travel', '여행후기'), ('good', '숙소추천'), ('free', '자유')], default='free', max_length=20),
        ),
    ]
