# Generated by Django 4.2.11 on 2024-07-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homst', '0019_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('여행후기', '여행후기'), ('숙소추천', '숙소추천'), ('자유', '자유')], default='free', max_length=20),
        ),
    ]
