# Generated by Django 4.2.11 on 2024-07-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homst', '0027_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('review', '여행 후기'), ('accommodation', '숙소 추천'), ('free', '자유')], default='free', max_length=20),
        ),
    ]
