# Generated by Django 4.2.11 on 2024-07-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homst', '0031_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
