# Generated by Django 4.2.11 on 2024-07-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homst', '0036_accommodationimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccommodationImage',
        ),
    ]
